### ISSUE TITLE
Most of the recipes are broken (except qemu and chroot)

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon-recipes#12]
Because of the last refactoring docker recipe is broken. Mostly cause of the extend path but I tried to fix it and it seems that there is more to do.

I think we need a CI tool that build each recipe regularly to not let that happen anymore.

**Comment by SalemHarrache** [comment]
I already tested the last refactoring before merging master on stable.

Was there any messages or something specific about this error ?

Which kameleon version were you using when this error occurred ?

+1 for CI testing ;-) (maybe we should try with travis-ci)

**Comment by mickours** [comment]
I fixed the other recipes then docker with 13b57dd33

**Comment by SalemHarrache** [comment]
Cool ! 
thanks :)
