### ISSUE TITLE
"local" variables aren't conserved when retry

### ISSUE THREAD

**Issue by ArthurGarnier** [oar-team/kameleon-recipes#14]
Hi,

In a recipe in Grid'5000 we have a small bash script in a first exec_in which define a variable which is followed by a second exec_in. This one, use the variable defined in the first. 

It works, but if the second exec fail, when we retry kameleon lost our variable. 

The script : 

- run_puppet:                                                                                         
  - exec_in: |                                                                                        
      if [ -z "$$variant" ]; then                                                                     
        VARIANT=std                                                                                   
      else                                                                                            
        VARIANT=$$variant                                                                             
      fi                                                                                              
  - exec_in:  $$puppet_path/puppet apply -d --modulepath=$$puppet_build_path/modules:/etc/puppetlabs/code/env\
ironments/production/modules $$puppet_build_path/manifests/$VARIANT.pp | tee /tmp/puppet_exec.log     

Why kameleon don't keep the variable ? Is there a way to avoid this "issue".

**Comment by mickours** [comment]
Sorry for the delay. This seems to be a bug, thanks for the report. We will investigate that.

**Comment by mickours** [comment]
The issue has migrate migrate.
