### ISSUE TITLE
Allow the base rootfs images generated by the bootstrap-recipes to be mirrored on external services

### ISSUE THREAD

**Issue by ArthurGarnier** [oar-team/kameleon-recipes#16]
Hi,

Sometimes kameleon.imag.fr is down and kameleon recipies are dependent of rootfs images hosted in : http://kameleon.imag.fr/rootfs/x86_64/

Is there any way to host some images ourselves ? I mean host them and keep them updated ! According to the web page the files are not versioned

**Comment by npf** [comment]
Hi Arthur,

If you wish to use locally hosted images, you need to:
- change the URL in https://github.com/grid5000/environments-recipes/blob/master/chroot/base.yaml.
- host the the images: either copy the ones from kameleon.imag.fr or generate new ones (that's the role of the bootstrap-recipes)

Do you see something which would need changed in the kameleon recipes ?

**Comment by ArthurGarnier** [comment]
Thanks for your answer, but actually the problem is not "how can I host my own images and use them" but "how can I host **always updated** kameleon rootfs images which are currently hosted on kameleon.imag.fr ?"

We just want to avoid to be stuck when imag is out of service, but using the same images than kameleon.imag.fr

**Comment by mickours** [comment]
Ok I fixed recipes and @npf just change the way they are named and add dates + version and SHA1  checksum. Now as you can see in the kameleon website (http://kameleon.imag.fr/rootfs/x86_64/), for each images you have this:
```
[ ]	archlinux-cache.tar.xz	2015-09-14 20:55 	247M	 
[ ]	archlinux-cache.tar.xz.sha1sum	2016-06-21 11:52 	76 	 
[ ]	archlinux-cache_20150914-1.tar.xz	2015-09-14 20:55 	247M	 
[ ]	archlinux-cache_20150914-1.tar.xz.sha1sum	2016-06-21 11:52 	76 	 
[ ]	archlinux.tar.xz	2015-09-14 20:51 	214M	 
[ ]	archlinux.tar.xz.sha1sum	2016-06-21 11:51 	70 	 
[ ]	archlinux_20150914-1.tar.xz	2015-09-14 20:51 	214M	 
[ ]	archlinux_20150914-1.tar.xz.sha1sum	2016-06-21 11:51 	70
```
@ArthurGarnier is it OK for you?

**Comment by mickours** [comment]
I'm closing this. Don't hesitate to open it again if it is not satisfying for you.
