### ISSUE TITLE
No more template from scratch ?

### ISSUE THREAD

**Issue by pmorillon** [oar-team/kameleon-recipes#26]
Into the documentation we can see : 
```
The following templates are available in /home/mercierm/.kameleon.d/repos:
NAME                                       | DESCRIPTION
-------------------------------------------|-------------------------------------------------------------------------
...
default/from_image/ubuntu12.04             | Ubuntu 12.04 LTS base system.
default/from_image/ubuntu14.04             | Ubuntu 14.04 LTS base system.
...
default/from_scratch/ubuntu12.04           | Ubuntu 12.04 LTS base system.
default/from_scratch/ubuntu14.04           | Ubuntu 14.04 LTS base system.
```

Now we using this repository we just have templates from images : 
```
root@parasilo-5:~# kameleon template repo add default https://github.com/oar-team/kameleon-recipes.git
```

Some templates using debootstrap would be great in order to create an image not available on `http://kameleon.imag.fr/rootfs/x86_64/` like an Ubuntu 16.04. Is there another repository with such templates ?

**Comment by mickours** [comment]
These template are in the refactor branch. This is not merge to master because we lack of manpower to do test and debug all recipes, but you can try the from_scratch templates (that are limited to qemu backend) they should work.
Any feedback on this branch is appreciated so we can merge it to master ASAP.

**Comment by pmorillon** [comment]
I will try templates from refactor branch. Thanks !
