### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by HugoGuiroux** [oar-team/kameleon-recipes#29]
Hi everyone,

Do you plan to release an image version of ubuntu xenial (16.04) similar to the ones available at http://kameleon.imag.fr/rootfs/x86_64/ ?

**Comment by mickours** [comment]
Sorry but we have troubles to build this environment and we do not have the time to find a workaround. We keep you posted.

**Comment by HugoGuiroux** [comment]
I have tried to build it from scratch similarly to ubuntu14.04, but it seems that the machine is stuck after the reboot. Did you face the same issue?

**Comment by lnussbaum** [comment]
Hi,

@mickours , on the grid'5000 side, we would also be interested in building Ubuntu 16.04 images. So more info on the problem you encountered would be helpful.

**Comment by npf** [comment]
Hugo, did you use the netinstall of the debootstrap recipe ?

The netinstall recipe is ok for zesty (17.04) but xenial (16.04) fails in the boot phase of the netinstall iso.

see branch npf/refactor

**Comment by npf** [comment]
Found a workaround. 16.04 netinstall is now ok.
