### ISSUE TITLE
Grid5k images ?

### ISSUE THREAD

**Issue by adfaure** [oar-team/kameleon-recipes#41]
Hello, 

I am trying to build a Debian image for gr5k, is there an up to date tutorial that I could use?
I would like to have a base image, and add my software stack by adding a few steps.

So far I tried:
https://www.grid5000.fr/w/User:Mmercier/Extend_grid5000_images
http://kameleon.imag.fr/grid5000_admin_tutorial.html

And also the recipes from, (in the folder grid5000), which seems outdated (last update 2 years from now).
https://gitlab.inria.fr/grid5000/environments-recipes.

Thank you.

**Comment by adfaure** [comment]
I think I found what I needed: https://gitlab.inria.fr/evalys/big-data-hpc-g5k-expe-tools/tree/master/environments

**Comment by mickours** [comment]
I just added this link to the grid5000 kameleon wiki page. Cleaning the recipes an provide an updated tutorial would be helpful.

**Comment by npf** [comment]
This question should have gone to Grid'5000 users' list.
